# Site settings
title: Documentation
project_title: UC Libraries Digital Collection
project_wiki: https://wiki.library.ucsf.edu/display/UCLDC/UCLDC+Implementation
date: November 4, 2015
email: ucldc@ucop.edu
description: ""
# baseurl: ""
baseurl: "/ucldc-docs"
# url: "http://0.0.0.0:4000"
url: "http://ucldc.github.io"
username: ucldc

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

collections:
  getting-started:
    output: true
    permalink: /getting-started/:path/
  calisphere:
    output: true
    permalink: /calisphere/:path/
  dpla: 
    output: true
    permalink: /dpla/:path/
  oac:
    output: true
    permalink: /oac/:path/
  dams:
    output: true
    permalink: /dams/:path/
  technical:
    output: true
    permalink: /technical/:path/

defaults:
  - scope:
      path: ""
      type: getting-started
    values:
      layout: doc
  - scope:
      path: ""
      type: calisphere
    values:
      layout: doc
  - scope:
      path: ""
      type: dpla
    values:
      layout: doc
  - scope:
      path: ""
      type: oac
    values:
      layout: doc
  - scope:
      path: ""
      type: dams
    values:
      layout: doc
  - scope:
      path: ""
      type: technical
    values:
      layout: doc